version: "1"
services:
  commerce-project:
    image: mysql:8.0.32
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: commerce
      MYSQL_USER: user
      MYSQL_PASSWORD: testpassword
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

